# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=1000)),
                ('Owner', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Number', models.IntegerField()),
                ('Owner', models.CharField(max_length=250)),
            ],
        ),
    ]
