# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Description',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='recipedetails',
            old_name='Owner',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oracle.Recipe'),
        ),
    ]
