# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0002_auto_20161101_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='decription',
            field=models.CharField(max_length=250),
        ),
    ]
