# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0004_remove_recipe_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='name',
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
