# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0005_auto_20161102_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='decription',
            new_name='description',
        ),
    ]
